services:
  api:
    build: .
    container_name: start-page
    ports:
      - "8080:8080"
    volumes:
      - /sys/class/thermal:/sys/class/thermal:ro
      - /sys/class/hwmon:/sys/class/hwmon:ro
      - /:/host:ro
      - ~/pew:/vault
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
      - Vault__VaultPath=/vault
      - Vault__DailyNotesFolder=Daily Notes
