name: Build and Push Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} http://peter:peter@gitea-http.default.svc.cluster.local:3000/peter/start-page.git .
          git checkout ${{ github.sha }}

      - name: Login to Gitea Registry
        run: docker login gitea-http.default.svc.cluster.local:3000 -u peter -p peter

      - name: Build and push
        run: |
          docker build -t gitea-http.default.svc.cluster.local:3000/peter/start-page:${{ github.sha }} -t gitea-http.default.svc.cluster.local:3000/peter/start-page:latest .
          docker push gitea-http.default.svc.cluster.local:3000/peter/start-page:${{ github.sha }}
          docker push gitea-http.default.svc.cluster.local:3000/peter/start-page:latest
